keyfrases = [
    "bullish trend", "rising value", "price surge", "strong earnings", "revenue growth",
    "positive outlook", "record profits", "solid performance", "market rally",
    "increased demand", "profit expansion", "strong quarter", "growth momentum",
    "improved forecast", "earnings beat", "steady recovery", "investor confidence",
    "new highs", "buyback announcement", "dividend increase", "robust demand",
    "expanding margins", "positive cash flow", "upward momentum", "bullish reversal",
    "long-term growth", "record revenue", "accelerating growth", "positive guidance",
    "sector strength", "improving fundamentals", "favorable market", "demand rebound",
    "increasing volume", "new opportunities", "sustained growth", "strategic acquisition",
    "innovation boost", "product expansion", "market leadership", "competitive advantage",
    "outperform expectations", "optimistic forecast", "increasing valuation",
    "improving economy", "strong sector performance", "positive sentiment",
    "record-breaking quarter", "profitability boost", "earnings surprise",
    "diversified portfolio", "upward breakout", "price recovery", "growth potential",
    "earnings growth", "strong liquidity", "credit upgrade", "expanding operations",
    "cost efficiency", "strong management", "strategic partnership", "international expansion",
    "new product launch", "favorable policy", "technological innovation",
    "revenue acceleration", "positive investor sentiment", "new market entry",
    "record cash flow", "steady performance", "high investor confidence",
    "resilient growth", "increasing profitability", "shareholder value creation",
    "stock outperformance", "market optimism", "new contracts", "growing portfolio",
    "revenue diversification", "record valuation", "improving credit outlook",
    "solid balance sheet", "margin expansion", "positive momentum", "strategic merger",
    "innovation leadership", "upward revision", "increased production", "strong demand outlook",
    "resilient sector", "operational improvement", "strong cash position",
    "positive quarterly results", "expanding customer base", "bullish indicator",
    "uptrend confirmation", "technical breakout", "recovery trend", "high market confidence",
    "earnings upside", "valuation upgrade", "market expansion", "sustained profitability",
    "upward trajectory", "record-setting profits", "favorable economic conditions",
    "industry rebound", "growth catalysts", "investor optimism", "market strength",
    "shareholder returns", "strong brand performance", "increased guidance",
    "record-breaking earnings", "positive revisions", "long-term bullish outlook",
    "financial resilience", "expanding profitability", "sector recovery",
    "strong fundamentals", "sustainable growth", "earnings momentum",
    "bearish trend", "falling price", "weak forecast", "loss warning", "negative outlook",
    "declining revenue", "market selloff", "profit drop", "earnings miss", "economic slowdown",
    "revenue decline", "bear market", "reduced demand", "margin compression",
    "cash flow concerns", "rising costs", "supply chain disruption", "regulatory pressure",
    "high volatility", "stock slump", "market uncertainty", "operational loss",
    "debt burden", "inflation pressure", "falling earnings", "weak demand",
    "price correction", "investor fear", "growth slowdown", "earnings downgrade",
    "profit erosion", "recession fears", "credit risk", "financial instability",
    "weak quarter", "guidance cut", "underperform expectations", "market correction",
    "valuation concern", "reduced guidance", "demand slowdown", "price decline",
    "negative sentiment", "sector weakness", "economic risk", "sell pressure",
    "lower margins", "uncertain outlook", "debt default", "funding issues",
    "negative earnings surprise", "slowing momentum", "market turbulence",
    "operational inefficiency", "sales drop", "profit warning", "weaker guidance",
    "declining margins", "increasing competition", "regulatory uncertainty",
    "rising inflation", "declining cash flow", "production slowdown", "falling demand",
    "rising debt levels", "increased risk exposure", "earnings pressure",
    "credit downgrade", "reduced profitability", "lower valuation", "market fear",
    "revenue headwinds", "macroeconomic slowdown", "weak sector performance",
    "loss expansion", "profit decline", "negative return", "market panic",
    "debt restructuring", "revenue contraction", "negative growth", "profit warning issued",
    "missed expectations", "credit stress", "liquidity shortage", "stock downgrade",
    "demand contraction", "lower outlook", "market instability", "price collapse",
    "economic headwinds", "debt accumulation", "revenue deterioration",
    "earnings disappointment", "market retreat", "downside risks", "inflation spike",
    "weak macro data", "rate hike concerns", "monetary tightening", "recession threat",
    "economic contraction", "financial distress", "operational challenges",
    "margin decline", "revenue slowdown", "profit margin pressure", "earnings weakness",
    "sector downturn", "fiscal concerns", "global slowdown", "market weakness",
    "economic decline", "bearish reversal", "declining outlook", "negative performance",
    "price stagnation", "sell-off pressure", "reduced investor confidence",
    "credit tightening", "market downturn", "profit slump", "financial weakness",
    "equity decline", "debt crisis", "market crash", "economic uncertainty",
    "fund outflows", "weaker fundamentals", "demand weakness", "price weakness",
    "rising unemployment", "currency depreciation", "interest rate pressure",
    "negative inflation outlook", "decreasing valuations", "asset devaluation",
    "lower investor sentiment", "profit contraction", "earnings volatility",
    "financial losses", "sector instability", "downward momentum", "investor caution"
]
